src/components/Chart/purechart.jsx
* onTooltipChange is work on Chart component
* onChange is work on Tooltip component
* If you set both at the same time，the callback on Tooltip will be called later
=> fix onToolTipChange isn't call

plugin/slider/README.md
=> 完善Slider README

.gitignore, demo/candlestick/basic.html, demo/other/cutomize-legend.html, demo/other/rain-and-flow.html, demo/summary.js
=> 提交支持slider的demo

demo/candlestick/basic.html, demo/other/rain-and-flow.html
=> 提交修改json地址错误问题

.eslintrc, package.json, testDemo/component/axis/adddelete.js, testDemo/component/axis/index.js, testDemo/component/axis/updateRect.js, testDemo/component/coord/adddelete.js, testDemo/component/coord/index.js, testDemo/component/coord/updateHelix.js, testDemo/component/coord/updatePolar.js, testDemo/component/coord/updateRect.js, testDemo/component/coord/updateTheta.js, testDemo/component/index.js
=> Compat react16

doc/api/dataset.md, doc_en/api/dataset.md
=>  translation dataset api for English

testDemo/component/geom/adddelete.js, testDemo/component/geom/index.js, testDemo/component/geom/updateRect.js, testDemo/component/index.js
Geom 组件add delete 有问题，图形只增不减， 同事data 渲染也有问题
=> 提交geom测试修改

testDemo/component/index.js, testDemo/component/legend/adddelete.js, testDemo/component/legend/index.js, testDemo/component/legend/updateRect.js, testDemo/component/tooltip/adddelete.js, testDemo/component/tooltip/index.js, testDemo/component/tooltip/updateRect.js
Tooltip HTML配置不显示， crosshair不更新
=> 提交tooltip测试

doc_en/README.md, doc_en/faq/faq.md, doc_en/tutorial/animate.md, doc_en/tutorial/interaction.md, doc_en/tutorial/theme.md
translate and fix url redirect
=> translation: theme & FAQ

doc_en/tutorial/data.md
=> translate data tutorial

typings/bizcharts-tests.tsx, typings/g2.d.ts, typings/index.d.ts, typings/tsconfig.json, typings/tslint.json
=> support ts

doc_en/tutorial/dataset.md
This is a first pass at improving the english DataSet documentation. There were a few areas where I was unclear of the meaning of the documentation - I left those unchanged.
Please let me know if there are any changes I can make to this PR to make it more mergeable.
=> Improve english wording of DataSet documentation

typings/index.d.ts
Added exports for few `type` like `GeomType` and also fixed few improper typings exports
=> Updated typings

src/index.d.ts, typings/index.d.ts
=> fix g2 reference of .d.ts

plugin/slider/package.json, plugin/slider/webpack.config.js, src/index.d.ts, typings/index.d.ts
slider packegejson and fix d.ts
close #249  #210
=> slider packege and fix d.ts

src/index.d.ts, typings/index.d.ts
=> type of scale

typings/index.d.ts
add missing return type of `_refCallback`
=> add missing return type of `_refCallback`

.github/issue_template.md
=> Create  issue_template

demo/relation/sankey.html
=> feature: sankey edge tooltip.

demo/component/guage/color.js
Fix guage color demo
close alibaba/BizCharts#355
=> fix: fix guage color demo

README.md
BizCharts: a powerful data visualization library based **on** G2 React.
=> Fix some expression

doc/api/label.md
https://github.com/alibaba/BizCharts/issues/456
=> Fix Label textStyle callback documentation

README.md
add feature : React es6 grammar
=> Update README.md add feature : React es6 grammar

doc/api/coord.md, src/processor/g2Creator.js, src/processor/g2Update.js
=> fix array value of coord reflect

typings/index.d.ts
```ts
<Axis
key="axis-y"
name="y"
label={false}
line={false}
tickLine={false}
grid={false}
{...yAxis}
/>
<Tooltip
showTitle={false}
crosshairs={false}
/>
```
=> support use ts  like ant-design-pro

typings/index.d.ts
fix GeomType missing 'lineStack'.
=> fix:typings, GeomType missing 'lineStack'

.prettierignore, .prettierrc, package.json, src/components/Chart/purechart.jsx
一图胜千言
pr 背景： 
https://github.com/ant-design/ant-design-pro/issues/4052
=> add resizeObserver

typings/index.d.ts
=> fix axis props ts typings

src/components/Chart/purechart.jsx
会造成这个问题
https://github.com/ant-design/ant-design-pro/issues/4107
=> add unobserve function

typings/index.d.ts
update typings of placeholder, htmlContent and itemTpl
=> types: update typings

typings/index.d.ts
=> fix: 修复LegendPositionType类型定义

typings/index.d.ts
=> fix AxisTitle

doc/api/label.md
=> fix: add missing }

src/components/Base/index.jsx
=> feat: add displayName to TypedComponent

src/components/Annotation/index.tsx
=> Correct the exported name

src/components/Axis/index.tsx, src/components/Chart/index.tsx, src/components/Coordinate/index.tsx, src/components/Interaction/index.tsx, src/components/Legend/index.tsx, src/components/Slider/index.tsx, src/components/Tooltip/index.tsx, src/components/View/index.tsx, src/interface.ts
=> feat: 添加ts提示校验

package.json
Improve npm repository information
=> add repository info

demos/g-components/basic.tsx, package.json, src/components/Chart/events.ts, src/components/View/viewHelper.ts, src/geometry/Base.tsx, src/index.tsx, src/utils/data-transform/minifyNum.ts, src/utils/data-transform/splitBySeparator.ts, src/utils/index.ts
=> 4.0.6 fix Safari reg bug

src/plots/index.tsx
=> Fix duplicate export

package.json
=> fixes #1223

package.json, src/createPlot.tsx
4.0.13 
- 升级 plot 依赖版本
-  plot组件的forceUpdate
=> feat: plot组件的forceUpdate

package.json, src/components/Chart/chartHelper.ts
https://huntr.dev/users/alromh87 has fixed the Cross-site Scripting (XSS) vulnerability 🔨. alromh87 has been awarded $25 for fixing the vulnerability through the huntr bug bounty program 💵. Think you could fix a vulnerability like this?
Get involved at https://huntr.dev/
Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/BizCharts/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/npm/bizcharts/1/README.md
`bizcharts` is vulnerable to `Cross-Site Scripting (XSS)`.
Fixed by sanitizing using DOMPurify when updating chart props.
1. Clone repo `https://github.com/alibaba/BizCharts`
2. Install dependencies 'npm i'
3. Start local server 'npm start'
4. Open the demo …
=> Security Fix for Cross-site Scripting (XSS) - huntr.dev
